### ISSUE TITLE
Access to bitrix 

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/web#12]
Need to get login info from Curtis, or do we need to start from scratch?

**Comment by ZulemaTMH** [comment]
@GeorgeBellTMH I texted Curtis again this morning and he said he would take care of it today. If you don't get anything today - let me know.
I've also asked another volunteer who has been working w/ Curtis, Nathan Jory, for help. Hopefully we'll get you connected soon.

**Comment by GeorgeBellTMH** [comment]
Got licensing info from Curtis.  Closing issue.
