### ISSUE TITLE
On the One Story home page in the platform, it only shows Overview and Early Years in the menu on the left hand side.  Shouldn't it also show Kids and Jr. High?

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/web#86]

**Comment by GeorgeBellTMH** [comment]
It should. @lucastbelem can you verify the permissions for Matt's account?

**Comment by GeorgeBellTMH** [comment]
Also @MattMilesJC sorry I didn't see this earlier, we don't use/monitor the web project - only the mobile project is active.

**Comment by lucastbelem** [comment]
@MattMilesJC you should be able to see it now Matt. Just had to adjust your permission.
